-- Axon Mind v5: Tablas para Neuro-Hacks (Inbox, Cerebro y Cierre Cognitivo)

-- 1. Tabla para la Bandeja de Entrada (Captura Rápida)
CREATE TABLE IF NOT EXISTS public.inbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla para los Documentos del Cerebro (Vault)
CREATE TABLE IF NOT EXISTS public.vault_docs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    cover_image TEXT,
    area TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla para el Cierre Cognitivo Diario (Journal de Pareja)
DROP TABLE IF EXISTS public.daily_journal;
CREATE TABLE IF NOT EXISTS public.daily_journal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile TEXT NOT NULL DEFAULT 'Tati', -- Tati o Pipe
    energy_level INTEGER, -- 1 al 5
    focus_level INTEGER, -- 1 al 5
    stress_level INTEGER, -- 1 al 5
    sleep_hours NUMERIC, -- Horas dormidas
    mood TEXT, -- Emoción principal (emoji)
    wins TEXT, -- Gratitud / Victorias
    family_impact TEXT, -- ¿Cómo impacté a mi familia/entorno hoy?
    life_lesson TEXT, -- ¿Qué haría diferente?
    frustrations TEXT, -- ¿Qué me robó la paz? (Descarga mental)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS explícitamente pero permitir todo (Método más confiable en Supabase)
ALTER TABLE public.inbox ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for inbox" ON public.inbox;
CREATE POLICY "Allow all for inbox" ON public.inbox FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.vault_docs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for vault" ON public.vault_docs;
CREATE POLICY "Allow all for vault" ON public.vault_docs FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.daily_journal ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for journal" ON public.daily_journal;
CREATE POLICY "Allow all for journal" ON public.daily_journal FOR ALL USING (true) WITH CHECK (true);
